server:
  port: 8081
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/auth
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
# auto-create-ddl option
    generate-ddl: true
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
    root: debug

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
    client:
      client-id: fc9815d4-3a6e-4d76-9f36-0b1bf2db40fb
      client-secret: fc9815d4-3a6e-4d76-9f36-0b1bf2db40fb