server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/auth
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
# auto-create-ddl option
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace