--
create table tb_partner (
        partner_no int8 generated by default as identity,
        created_at timestamp,
        created_by varchar(255),
        updated_at timestamp,
        updated_by varchar(255),
        partner_company_name varchar(50) not null,
        partner_email varchar(50) not null,
        partner_id varchar(50) not null,
        partner_password varchar(100) not null,
        partner_status varchar(255),
        primary key (partner_no)
)

create table tb_partner_role (
        partner_no int8 not null,
        partner_role varchar(10) not null,
        primary key (partner_no, partner_role)
)

alter table if exists tb_partner
    add constraint PARTNER_ID_UNIQUE unique (partner_id)

alter table if exists tb_partner_role
    add constraint TB_PARTNER_ROLE_PARTNER_NO_FOREIGN_KEY
    foreign key (partner_no)
    references tb_partner

--
create table tb_client (
       client_id varchar(255) not null,
       created_at timestamp,
       created_by varchar(255),
       updated_at timestamp,
       updated_by varchar(255),
       access_token_validity int4,
       additional_information varchar(255),
       authorities varchar(255),
       authorized_grant_types varchar(255),
       auto_approve boolean,
       client_secret varchar(255),
       refresh_token_validity int4,
       resource_ids varchar(255),
       scope varchar(255),
       partner_no int8 not null,
       primary key (client_id)
)

alter table if exists tb_client
    add constraint TB_CLIENT_PARTNER_NO_FOREIGN_KEY
    foreign key (partner_no)
    references tb_partner
